"""initial migration

Revision ID: 696f4d4547db
Revises: 
Create Date: 2024-09-27 03:21:15.957055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696f4d4547db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athletes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_name', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('distance', sa.String(length=255), nullable=False),
    sa.Column('result', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], name=op.f('fk_activities_athlete_id_athletes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('race_participations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('completion_time', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], name=op.f('fk_race_participations_athlete_id_athletes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], name=op.f('fk_race_participations_race_id_races'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('race_participations')
    op.drop_table('activities')
    op.drop_table('races')
    op.drop_table('athletes')
    # ### end Alembic commands ###
